### PR TITLE
Replace Algolia with site search

### PR DESCRIPTION
**Pull request by freekmurze**

### CODE REVIEW

**Comment by riasvdv** [comment]
image

Added styles + Alpine.js store and functionality of the modal

**Comment by freekmurze** [comment]
Very nice!

Could we use the exact Spatie blue from our logo here?

**Comment by riasvdv** [comment]
I tried that but felt it was too heavy, this also a color from our existing tailwind file

**Comment by freekmurze** [comment]
Ok! I'll deploy this early next week 👍

**Comment by freekmurze** [comment]
Thanks!

**Pull request merged**
