### PR TITLE
Add a second notification for expired licenses

### PR DESCRIPTION
**Pull request by riasvdv**
I've added the scaffolding for a second notification.

The copy should probably be updated a bit.

We also want to add the advantages of the product you're renewing the license for. How do we want to do this? Do we add an extra field to the Purchasables in Nova? Something like "mail_advantages"?

### CODE REVIEW

**Comment by willemvb** [comment]
Pushed some copy tweaks.

Adding an extra field sounds good to me. Maybe make the field name a bit more explicit?
eg. `renewal_mail_incentive`

**Review by willemvb — APPROVED** [review]

**Comment by riasvdv** [comment]
> Adding an extra field sounds good to me. Maybe make the field name a bit more explicit?
> eg. `renewal_mail_incentive`

Great! I'll add that this week

**Comment by riasvdv** [comment]
@willemvb I added some routes that are only available in a local environment to test the notifications:

- /dev/mails/license-expires-soon
- /dev/mails/license-expired
- /dev/mails/license-expired-second

Maybe we should give these mails a bit more of a "Spatie" look as well?

image

I've added the incentives in a new line just above the button in the 3 mails

**Comment by riasvdv** [comment]
Added a header + tweaked the colors a bit

image

**Comment by freekmurze** [comment]
Very nice!

**Pull request merged**
