### PR TITLE
Update Laravel-Permission package branch for new release.

### PR DESCRIPTION
**Pull request by drbyte**
Just released v6

### CODE REVIEW

**Comment by freekmurze** [comment]
What a release list 👍 
https://github.com/spatie/laravel-permission/releases

Thanks for taking care of all of this! 👏

**Comment by drbyte** [comment]
@freekmurze do you know why the docs site would be showing both v5 and v6 as built from `main`?

Screen Shot 2023-10-28 at 11 17 52 AM

**Comment by drbyte** [comment]
Oops. I keep forgetting that the _index.md needs updating for major versions!
Fixed.

Screen Shot 2023-10-28 at 11 25 36 AM
Screen Shot 2023-10-28 at 11 25 07 AM

**Comment by freekmurze** [comment]
No worries, I always forget this too 🙂

**Pull request merged**
